services:
  - docker

script:

## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed nthuu1001/udagram-api-feed:v1
  - docker tag udagram-api-user nthuu1001/udagram-api-user:v1
  - docker tag udagram-frontend nthuu1001/udagram-frontend:v1
  - docker tag udagram-reverseproxy nthuu1001/udagram-reverseproxy:v1

after success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push nthuu1001/udagram-api-feed:v1
    - docker push nthuu1001/udagram-api-user:v1
    - docker push nthuu1001/udagram-frontend:v1
    - docker push nthuu1001/reverseproxy:v1